# Air config for hot-reload in development
root = "."

[build]
cmd = "go build -o ./tmp/server ./cmd/api"
bin = "./tmp/server"
full_bin = "./tmp/server"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules", "web/.next", "web/node_modules", "logs"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
